version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: de_assessment_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assessment_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d assessment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
